import { DATABASE } from "./constants";

export const WORKFLOW_SESSION_INSTANCES = `WITH LatestTaskVersion AS (
SELECT
	INSTANCE_ID,
	WORKFLOW_ID,
	MAX(VERSION_NUMBER) AS LATEST_VERSION
FROM
	${DATABASE}.OPB_TASK_INST
GROUP BY
	INSTANCE_ID,
	WORKFLOW_ID
),
LatestExprVersion AS (
SELECT
	WORKFLOW_ID,
	CONDITION_ID,
	MAX(VERSION_NUMBER) AS LATEST_VERSION
FROM
	${DATABASE}.OPB_WFLOW_EXPR
GROUP BY
	WORKFLOW_ID,
	CONDITION_ID
)
SELECT
	owd.FROM_INST_ID,
	owd.TO_INST_ID,
	owd.CONDITION_ID,
	oexpr.CONDITION,
	oti_from.TASK_ID AS FROM_TASK_ID,
	oti_from.INSTANCE_NAME AS FROM_INST_NAME,
	oti_from.TASK_TYPE AS FROM_INST_TASK_TYPE,
	(SELECT OBJECT_TYPE_NAME FROM ${DATABASE}.OPB_OBJECT_TYPE oot WHERE OBJECT_TYPE_ID = OTI_FROM.TASK_TYPE) AS FROM_INST_TASK_TYPE_NAME,
	oti_to.TASK_ID AS TO_TASK_ID,
	oti_to.INSTANCE_NAME AS TO_INST_NAME,
	oti_to.TASK_TYPE AS TO_INST_TASK_TYPE,
	(SELECT OBJECT_TYPE_NAME FROM ${DATABASE}.OPB_OBJECT_TYPE oot WHERE OBJECT_TYPE_ID = OTI_TO.TASK_TYPE) AS TO_INST_TASK_TYPE_NAME
FROM
	${DATABASE}.OPB_WFLOW_DEP owd
JOIN ${DATABASE}.OPB_TASK_INST oti_from
    ON
	oti_from.INSTANCE_ID = owd.FROM_INST_ID
	AND oti_from.WORKFLOW_ID = owd.WORKFLOW_ID
	AND oti_from.VERSION_NUMBER = (
	SELECT
		LATEST_VERSION
	FROM
		LatestTaskVersion
	WHERE
		INSTANCE_ID = owd.FROM_INST_ID
    )
	-- AND oti_from.IS_ENABLED = 1
	-- AND oti_from.IS_VALID = 1
JOIN ${DATABASE}.OPB_TASK_INST oti_to
    ON
	oti_to.INSTANCE_ID = owd.TO_INST_ID
	AND oti_to.WORKFLOW_ID = owd.WORKFLOW_ID
	AND oti_to.VERSION_NUMBER = (
	SELECT
		LATEST_VERSION
	FROM
		LatestTaskVersion
	WHERE
		INSTANCE_ID = owd.TO_INST_ID
    )
	-- AND oti_to.IS_ENABLED = 1
	-- AND oti_to.IS_VALID = 1
JOIN ${DATABASE}.OPB_WFLOW_EXPR oexpr
    ON
	oexpr.WORKFLOW_ID = owd.WORKFLOW_ID
	AND oexpr.CONDITION_ID = owd.CONDITION_ID
	AND oexpr.VERSION_NUMBER = (
	SELECT
		LATEST_VERSION
	FROM
		LatestExprVersion
	WHERE
		WORKFLOW_ID = owd.WORKFLOW_ID
		AND CONDITION_ID = owd.CONDITION_ID
    )
WHERE
	owd.WORKFLOW_ID = (
	SELECT
		DISTINCT WORKFLOW_ID
	FROM
		${DATABASE}.REP_TASK_INST_RUN rtir
	WHERE
		WORKFLOW_NAME = :WORKFLOWNAME
		AND SUBJECT_AREA = :SUBJECTAREANAME
)
	AND owd.VERSION_NUMBER = (
	SELECT
		MAX(VERSION_NUMBER)
	FROM
		${DATABASE}.OPB_WFLOW_DEP owd2
	WHERE
		owd.WORKFLOW_ID = owd2.WORKFLOW_ID
    )`;

export const SUB_WF = `SELECT 
	OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA,
	OPB_WFLOW_RUN.WORKFLOW_NAME
FROM 
    ${DATABASE}.OPB_TASK_INST_RUN OPB_TASK_INST_RUN, ${DATABASE}.OPB_WFLOW_RUN OPB_WFLOW_RUN, ${DATABASE}.OPB_SUBJECT OPB_SUBJECT
WHERE 
	OPB_SUBJECT.SUBJ_ID = OPB_TASK_INST_RUN.SUBJECT_ID
	AND OPB_WFLOW_RUN.WORKFLOW_ID = OPB_TASK_INST_RUN.WORKFLOW_ID 
GROUP BY OPB_SUBJECT.SUBJ_NAME, OPB_WFLOW_RUN.WORKFLOW_NAME
ORDER BY OPB_SUBJECT.SUBJ_NAME`;

export const INSTANCES = `SELECT    
    OPB_OBJECT_TYPE.OBJECT_TYPE_NAME AS TASK_TYPE_NAME,
    OPB_TASK_INST_RUN.TASK_NAME
FROM 
    ${DATABASE}.OPB_TASK_INST_RUN
JOIN 
    ${DATABASE}.OPB_OBJECT_TYPE ON ${DATABASE}.OPB_TASK_INST_RUN.TASK_TYPE = ${DATABASE}.OPB_OBJECT_TYPE.OBJECT_TYPE_ID
JOIN 
    ${DATABASE}.OPB_WFLOW_RUN ON ${DATABASE}.OPB_TASK_INST_RUN.WORKFLOW_ID = ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_ID 
                                     AND ${DATABASE}.OPB_TASK_INST_RUN.WORKFLOW_RUN_ID = ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_RUN_ID 
JOIN 
    ${DATABASE}.OPB_SUBJECT ON ${DATABASE}.OPB_TASK_INST_RUN.SUBJECT_ID = ${DATABASE}.OPB_SUBJECT.SUBJ_ID
WHERE 
    ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_NAME = :workflowName
    AND ${DATABASE}.OPB_SUBJECT.SUBJ_NAME = :subjectAreaName
GROUP BY 
    ${DATABASE}.OPB_SUBJECT.SUBJ_NAME,
    ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_NAME,
    ${DATABASE}.OPB_OBJECT_TYPE.OBJECT_TYPE_NAME,
    ${DATABASE}.OPB_TASK_INST_RUN.TASK_NAME
ORDER BY OPB_SUBJECT.SUBJ_NAME
`;

export const INSTANCES_BAK = `
SELECT 
       rtir.TASK_TYPE_NAME, rtir.INSTANCE_NAME,
       MAX(START_TIME) START_TIME, 
       MAX(END_TIME) AS END_TIME
FROM ${DATABASE}.REP_TASK_INST_RUN rtir
JOIN ${DATABASE}.REP_TASK_INST rti ON rti.TASK_ID = rtir.TASK_ID AND rti.IS_ENABLED = 1
WHERE WORKFLOW_NAME = :workflowName
AND SUBJECT_AREA = :subjectAreaName
GROUP BY rtir.INSTANCE_ID, rtir.WORKFLOW_NAME, rtir.INSTANCE_NAME, rtir.TASK_TYPE_NAME, rtir.TASK_ID 
ORDER BY START_TIME ASC, END_TIME ASC, rtir.TASK_ID ASC
`;

export const COMMANDS = `
SELECT PM_VALUE, VAL_NAME FROM ${DATABASE}.OPB_TASK_VAL_LIST f
WHERE TASK_ID = (
	SELECT MAX(TASK_ID) FROM ${DATABASE}.REP_TASK_INST rti WHERE rti.INSTANCE_NAME = :taskName
	AND rti.WORKFLOW_ID = (SELECT MAX(WORKFLOW_ID) FROM ${DATABASE}.REP_WFLOW_RUN rwr WHERE rwr.WORKFLOW_NAME = :workflowName))
AND SUBJECT_ID = (SELECT MAX(SUBJECT_ID) FROM ${DATABASE}.REP_WFLOW_RUN rwr WHERE rwr.SUBJECT_AREA = :subjectAreaName)
AND VERSION_NUMBER = (SELECT MAX(VERSION_NUMBER) FROM ${DATABASE}.OPB_TASK_VAL_LIST g WHERE TASK_ID = f.TASK_ID AND SUBJECT_ID = f.SUBJECT_ID )
ORDER BY EXEC_ORDER
`;

export const EVENT_WAIT_FILE = `
SELECT ATTR_VALUE
FROM (
	SELECT ATTR_VALUE, ROW_NUMBER() OVER (ORDER BY VERSION_NUMBER DESC) RNK
	FROM
		(SELECT SUBJECT_AREA, WORKFLOW_NAME, INSTANCE_ID, INSTANCE_NAME, TASK_ID, TASK_TYPE_NAME,
			ROW_NUMBER() OVER (ORDER BY END_TIME DESC) RNK
		FROM INFA_REPO105_PROD.REP_TASK_INST_RUN R
		WHERE SUBJECT_AREA = :subjectAreaName
		  AND WORKFLOW_NAME = :workflowName
		  AND INSTANCE_NAME = :taskName) R,
	  	INFA_REPO105_PROD.OPB_TASK_ATTR O
	WHERE R.TASK_ID = O.TASK_ID
		AND RNK = 1
		AND ATTR_ID = 4)
WHERE RNK = 1
`;
