import { DATABASE } from "./constants";

export const SUB_WF = `SELECT 
	OPB_SUBJECT.SUBJ_NAME SUBJECT_AREA,
	OPB_WFLOW_RUN.WORKFLOW_NAME
FROM 
    ${DATABASE}.OPB_TASK_INST_RUN OPB_TASK_INST_RUN, ${DATABASE}.OPB_WFLOW_RUN OPB_WFLOW_RUN, ${DATABASE}.OPB_SUBJECT OPB_SUBJECT
WHERE 
	OPB_SUBJECT.SUBJ_ID = OPB_TASK_INST_RUN.SUBJECT_ID
	AND OPB_WFLOW_RUN.WORKFLOW_ID = OPB_TASK_INST_RUN.WORKFLOW_ID 
GROUP BY OPB_SUBJECT.SUBJ_NAME, OPB_WFLOW_RUN.WORKFLOW_NAME`;

export const INSTANCES = `SELECT    
    OPB_OBJECT_TYPE.OBJECT_TYPE_NAME AS TASK_TYPE_NAME,
    OPB_TASK_INST_RUN.TASK_NAME
FROM 
    ${DATABASE}.OPB_TASK_INST_RUN
JOIN 
    ${DATABASE}.OPB_OBJECT_TYPE ON ${DATABASE}.OPB_TASK_INST_RUN.TASK_TYPE = ${DATABASE}.OPB_OBJECT_TYPE.OBJECT_TYPE_ID
JOIN 
    ${DATABASE}.OPB_WFLOW_RUN ON ${DATABASE}.OPB_TASK_INST_RUN.WORKFLOW_ID = ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_ID 
                                     AND ${DATABASE}.OPB_TASK_INST_RUN.WORKFLOW_RUN_ID = ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_RUN_ID 
JOIN 
    ${DATABASE}.OPB_SUBJECT ON ${DATABASE}.OPB_TASK_INST_RUN.SUBJECT_ID = ${DATABASE}.OPB_SUBJECT.SUBJ_ID
WHERE 
    ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_NAME = :workflowName
    AND ${DATABASE}.OPB_SUBJECT.SUBJ_NAME = :subjectAreaName
GROUP BY 
    ${DATABASE}.OPB_SUBJECT.SUBJ_NAME,
    ${DATABASE}.OPB_WFLOW_RUN.WORKFLOW_NAME,
    ${DATABASE}.OPB_OBJECT_TYPE.OBJECT_TYPE_NAME,
    ${DATABASE}.OPB_TASK_INST_RUN.TASK_NAME
`;

export const INSTANCES_BAK = `
SELECT 
       TASK_TYPE_NAME, INSTANCE_NAME,
       MAX(START_TIME) START_TIME, 
       MAX(END_TIME) AS END_TIME
FROM ${DATABASE}.REP_TASK_INST_RUN
WHERE WORKFLOW_NAME = :workflowName
GROUP BY INSTANCE_ID, WORKFLOW_NAME, INSTANCE_NAME, TASK_TYPE_NAME, TASK_ID 
ORDER BY START_TIME ASC, END_TIME ASC, TASK_ID ASC
`;